Vagrant.configure("2") do |config|
  config.vm.define "windows10" do |swf03|
    # swf03.vm.box = "mcandre/windows"
    swf03.vm.box = "fishi0x01/win-10-pro-x64"
    swf03.vm.box_check_update = true
    swf03.vm.hostname = "swf-03"
    swf03.vm.communicator = "winrm"
    swf03.winrm.username = "vagrant"
    swf03.winrm.password = "vagrant"
    swf03.vm.network "private_network", ip: "192.168.56.4"
    swf03.vm.network :forwarded_port, guest: 3389, host: 33389, id: "rdp", auto_correct: true
    swf03.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
   
    swf03.vm.provision :shell do |shell|
     shell.path = "https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
    end
    swf03.vm.provision :shell, inline: "
       if ($PSVersionTable.PSVersion.Major -eq 4)
       {
         choco upgrade powershell -y
         shutdown /r /t 0
       }
       "
    swf03.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 2
    end
  end
end
